version: '3.8'

services:
  web:
    build: .
    container_name: education-worker-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./files:/var/www/html/files
      - ./uploads:/var/www/html/uploads
    environment:
      - DB_HOST=183.182.99.33
      - DB_PORT=5555
      - DB_USER=gennex
      - DB_PASS=Gennxe@123
      - DB_NAME=edu-pro
    restart: unless-stopped

